In [8]:
import torch as t
import numpy as np

## tensor
创建

In [10]:
# from list or np,array
x = t.tensor([[1,1],[1,1]])
x = t.tensor(np.ones((2,2)))
x = t.from_numpy(np.ones((2,2)))

tensor([[1., 1.],
        [1., 1.]], dtype=torch.float64)

In [11]:
# zero tensor
x = t.zeros([2,2])
# one tensor
x = t.ones([1,2,5])

tensor([[[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]]])

In [34]:
x.shape

torch.Size([1, 1, 1])

In [33]:
x.dtype

torch.float32

**注意：[1,2,5]和[2,5]并不一样，二者的维度上不同**

降维

In [17]:
# squeeze 删除一个张量中所有维数为1的维度
x = x.squeeze(0) # 参数的含义为删除指定位置的1，如果所给位置不是1，则无效，如此题，若给的参数是1，则不改变其形状
x.shape

torch.Size([2, 5])

升维

In [18]:
# unsqueeze 延展出一个新的维度
x = x.unsqueeze(1) # 在所给的位置延展维度
x.shape

torch.Size([2, 1, 5])

对调维度

In [21]:
x = x.transpose(1,2) # 要调换的维度
x.shape

torch.Size([2, 5, 1])

按特定的维度拼接矩阵

In [25]:
y = t.zeros([2,5,2])
z = t.zeros([2,5,3])
w = t.cat([x,y,z],dim=2)
w.shape

torch.Size([2, 5, 6])

运算

In [26]:
x = t.ones([1,1,1])
y = t.zeros([1,1,1])
x+y

tensor([[[1.]]])

In [27]:
x-y

tensor([[[1.]]])

In [29]:
x.pow(2)

tensor([[[1.]]])

In [30]:
x.sum()

tensor(1.)

In [31]:
x.mean()

tensor(1.)