In [2]:
import torch as t
import numpy as np

## tensor
创建

In [3]:
# from list or np,array
x = t.tensor([[1,1],[1,1]])
x = t.tensor(np.ones((2,2)))
x = t.from_numpy(np.ones((2,2)))

In [4]:
# zero tensor
x = t.zeros([2,2])
# one tensor
x = t.ones([1,2,5])

In [5]:
x.shape

torch.Size([1, 2, 5])

In [6]:
x.dtype

torch.float32

**注意：[1,2,5]和[2,5]并不一样，二者的维度上不同**

降维

In [7]:
# squeeze 删除一个张量中所有维数为1的维度
x = x.squeeze(0) # 参数的含义为删除指定位置的1，如果所给位置不是1，则无效，如此题，若给的参数是1，则不改变其形状
x.shape

torch.Size([2, 5])

升维

In [8]:
# unsqueeze 延展出一个新的维度
x = x.unsqueeze(1) # 在所给的位置延展维度
x.shape

torch.Size([2, 1, 5])

对调维度

In [9]:
x = x.transpose(1,2) # 要调换的维度
x.shape

torch.Size([2, 5, 1])

按特定的维度拼接矩阵

In [10]:
y = t.zeros([2,5,2])
z = t.zeros([2,5,3])
w = t.cat([x,y,z],dim=2)
w.shape

torch.Size([2, 5, 6])

运算

In [11]:
x = t.ones([1,1,1])
y = t.zeros([1,1,1])
x+y

tensor([[[1.]]])

In [12]:
x-y

tensor([[[1.]]])

In [13]:
x.pow(2)

tensor([[[1.]]])

In [14]:
x.sum()

tensor(1.)

In [15]:
x.mean()

tensor(1.)

#### GPU

In [16]:
x.to("cuda")

tensor([[[1.]]], device='cuda:0')

In [17]:
t.cuda.is_available()

True

#### 计算grad

In [19]:
x = t.tensor([[1.,0.],[-1.,1.]],requires_grad=True)
z = x.pow(2).sum()
z.backward()
x.grad

tensor([[ 2.,  0.],
        [-2.,  2.]])

#### load data

In [ ]:
from torch.utils.data import DataLoader,Dataset

class MyDataset(Dataset):  # 存储数据
    def __init__(self,file) -> None:
        super().__init__()
        self.data = open(file=file).read()
    
    def __getitem__(self, index):
        return self.data[index]
    
    def __len__(self):
        return len(self.data)

file = ""
dataset = MyDataset(file)
dataloader = DataLoader(dataset=dataset,batch_size="",shuffle=True) # 提取数据用
# 第二个参数指的是返回的数据集的大小，第三个参数为训练集为T，验证时为F

#### 线性

In [20]:
layer = t.nn.Linear(32,64)
layer.weight.shape

torch.Size([64, 32])

In [21]:
layer.bias.shape

torch.Size([64])

In [ ]:
import torch.nn as nn

class MyModel(nn.Module):
    def __init__(self) -> None:
        super().__init__()
        self.net = nn.Sequential( # 打包起来 
            nn.Linear(10,36),
            nn.Sigmoid(),
            nn.Linear(32,1)
        )# 10->32->1
    
    def forward(self,x):
        return self.net(x)