# 第二次课作业

In [33]:
import numpy as np
import random as rd

（1）创建一个1到10的数组，然后逆序输出。

In [2]:
l1 = np.array([i for i in range(1,11)])
l1[::-1]

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

（2）创建一个长度为20的全1数组，然后变成一个4×5的二维矩阵并转置。

In [4]:
l2 = np.ones(20).reshape(4,5).T
l2

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

（3）创建一个3x3x3的随机数组。
(提示: np.random.random)

In [6]:
np.random.random(9).reshape(3,3)

array([[0.08905812, 0.17217106, 0.7732834 ],
       [0.66158599, 0.63099004, 0.24219964],
       [0.69998161, 0.07019705, 0.92562218]])

（4）从1到10中随机选取10个数，构成一个长度为10的数组，并将其排序。获取其最大值最小值，求和，求方差。

In [13]:
l3=np.random.randint(1,11,10)
print(np.sort(l3))
print(l3.max())
print(l3.min())
print(l3.sum())
print(l3.std())

[ 2  2  3  4  5  5  7  9  9 10]
10
2
56
2.835489375751565


（5）从1到10中随机选取10个数，构成一个长度为10的数组，选出其中的奇数。

In [15]:
l4 = np.random.randint(1,11,10)
l4[l4%2==1]

array([5, 9, 1, 9, 9, 5, 3])

（6）生成0到100，差为5的一个等差数列，然后将数据类型转化为整数。

In [19]:
np.linspace(0,100,5).astype(int)

array([  0,  25,  50,  75, 100])

（7）从1到10中随机选取10个数，大于3和小于8的取负数。

In [24]:
l5 = np.random.randint(1,11,10)
l5[np.where((l5>3) & (l5<8))]*(-1)

array([-4, -7])

（8）在数组[1, 2, 3, 4, 5]中相邻两个数字中间插入1个0。

In [30]:
a = np.array([1,2,3,4,5])
result = np.zeros(9,dtype=int)
result[::2] = a
result

array([1, 0, 2, 0, 3, 0, 4, 0, 5])

（9）新建一个5乘5的随机二位数组，交换其中两行？比如交换第一二行。

注意变量指向问题

In [29]:
l6 = np.random.rand(25).reshape(5,5)
print(l6)
a = l6[1].copy()
l6[1]=l6[0].copy()
l6[0]=a
print(l6)

[[0.02774426 0.20970709 0.99138757 0.02740685 0.59517844]
 [0.65993441 0.99664105 0.60556336 0.56954096 0.50597384]
 [0.20700026 0.51921836 0.52650313 0.10388627 0.29909257]
 [0.6324416  0.94272616 0.0607537  0.5373395  0.3093455 ]
 [0.15263338 0.00720881 0.5701214  0.8562844  0.00986203]]
[[0.65993441 0.99664105 0.60556336 0.56954096 0.50597384]
 [0.02774426 0.20970709 0.99138757 0.02740685 0.59517844]
 [0.20700026 0.51921836 0.52650313 0.10388627 0.29909257]
 [0.6324416  0.94272616 0.0607537  0.5373395  0.3093455 ]
 [0.15263338 0.00720881 0.5701214  0.8562844  0.00986203]]


In [33]:
# 或者
# 靠，居然忘了这个
a[[1,0,2,3,4]]

array([[0.60248234, 0.0221739 , 0.96911108, 0.29489501, 0.81033611],
       [0.92933312, 0.28962428, 0.50480061, 0.97575003, 0.30676499],
       [0.15843057, 0.24986663, 0.15318215, 0.51171144, 0.19834456],
       [0.15863201, 0.56060046, 0.99896885, 0.92428774, 0.58047529],
       [0.06532111, 0.70728976, 0.86449164, 0.37043458, 0.44586781]])

（10）把一个10\*2的随机生成的笛卡尔坐标转换成极坐标。

In [43]:
a= np.random.rand(10)
b= np.random.rand(10)
c = (a**2+b**2)**0.5
d =  np.arctan(b/a)
np.dstack((c,d))

array([[[0.99876459, 0.09415922],
        [1.00261677, 1.24900697],
        [0.31190392, 0.44782497],
        [0.71107671, 0.78691781],
        [0.84120267, 0.98788066],
        [1.27521129, 0.71912554],
        [1.16409388, 0.96983385],
        [1.01892331, 0.55915572],
        [0.79539591, 0.20913614],
        [0.88472758, 0.1253597 ]]])

（11）创建一个长度为10并且除了第五个值为1其余的值为2的向量。

In [49]:
l = np.ones(10)
l.fill(2)
l[4]=1
l

array([2., 2., 2., 2., 1., 2., 2., 2., 2., 2.])

（12）创建一个长度为10的随机向量，并求其累计和。

In [36]:
x = rd.randint(1,11)
l = np.array([x,(100-x)**0.5])
np.cumsum(l)

array([11.        , 20.43398113])

（13）将数组中的所有奇数替换成-1。

In [32]:
l4 = np.random.randint(1,11,10)
l4[l4%2==1]=-1
l4

array([-1, -1,  6, 10,  8, -1,  8, 10, 10, -1])

（14）构造两个4乘3的二维数组，按照3种方法进行连接？

In [52]:
a = np.ones((4,3))
b = np.zeros((4,3))
print(np.vstack((a,b)))
print(np.dstack((a,b)))
print(np.hstack((a,b)))

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[[1. 0.]
  [1. 0.]
  [1. 0.]]

 [[1. 0.]
  [1. 0.]
  [1. 0.]]

 [[1. 0.]
  [1. 0.]
  [1. 0.]]

 [[1. 0.]
  [1. 0.]
  [1. 0.]]]
[[1. 1. 1. 0. 0. 0.]
 [1. 1. 1. 0. 0. 0.]
 [1. 1. 1. 0. 0. 0.]
 [1. 1. 1. 0. 0. 0.]]


（15）获取数组 a 和 b 中的共同项（索引位置相同，值也相同）。
a = np.array([1,2,3,2,3,4,3,4,5,6])，b = np.array([7,2,10,2,7,4,9,4,9,8])

In [60]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
c = a/b
a[c==1]

array([2, 2, 4, 4])

（16）从数组 a 中提取 5 和 10 之间的所有项。a=np.array([7,2,10,2,7,4,9,4,9,8])

In [63]:
a=np.array([7,2,10,2,7,4,9,4,9,8])
a[np.where((a>5)&(a<10))]

array([7, 7, 9, 9, 8])