# 第二次课作业

In [1]:
import numpy as np

（1）创建一个1到10的数组，然后逆序输出。

In [3]:
a =  np.arange(1,11)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
a[-1::-1]

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

（2）创建一个长度为20的全1数组，然后变成一个4×5的二维矩阵并转置。

In [6]:
a = np.ones([20])
b = a.reshape((4,5)).transpose()
b

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

（3）创建一个3x3x3的随机数组。
(提示: np.random.random)

In [7]:
a = np.random.random((3,3,3))
a

array([[[0.2332263 , 0.85456086, 0.96325769],
        [0.00532915, 0.69676662, 0.95731451],
        [0.92492736, 0.54803557, 0.8787475 ]],

       [[0.40752915, 0.7798283 , 0.8267187 ],
        [0.19474928, 0.41573032, 0.80379513],
        [0.38076987, 0.16058834, 0.09757234]],

       [[0.10515906, 0.04427701, 0.22620756],
        [0.70892571, 0.99494136, 0.37302098],
        [0.13936976, 0.31596893, 0.31861418]]])

（4）从1到10中随机选取10个数，构成一个长度为10的数组，并将其排序。获取其最大值最小值，求和，求方差。

In [14]:
a = np.random.randint(1,10,10)
a
a = np.sort(a)
a

array([1, 2, 2, 4, 5, 6, 7, 7, 7, 8])

In [15]:
max = a.max()
min = a.min()
print(max,min)

8 1


In [16]:
sum = a.sum()
var = a.var()
print(sum,var)

49 5.6899999999999995


（5）从1到10中随机选取10个数，构成一个长度为10的数组，选出其中的奇数。

In [18]:
a = np.random.randint(1,10,10)
print(a[a%2!=0],a)

[9 5 3 1 7 7 1 9] [9 5 3 1 8 7 7 6 1 9]


（6）生成0到100，差为5的一个等差数列，然后将数据类型转化为整数。

In [21]:
a = np.linspace(0,100,21)
a = a.astype(int)
a

array([  0,   5,  10,  15,  20,  25,  30,  35,  40,  45,  50,  55,  60,
        65,  70,  75,  80,  85,  90,  95, 100])

（7）从1到10中随机选取10个数，大于3和小于8的取负数。

In [28]:
a = np.random.randint(1,10,10)
a[(a>3) & (a<8)] = -1 * a[(a>3) & (a<8)]
a


array([-7,  1, -5, -6,  2,  3, -4, -7, -6, -7])

（8）在数组[1, 2, 3, 4, 5]中相邻两个数字中间插入1个0。

In [30]:
a = np.array([1,2,3,4,5])
result = np.zeros(9,dtype=int)
result[::2] = a
result

array([1, 0, 2, 0, 3, 0, 4, 0, 5])

（9）新建一个5乘5的随机二位数组，交换其中两行？比如交换第一二行。

In [31]:
a = np.random.random((5,5))
a

array([[0.60248234, 0.0221739 , 0.96911108, 0.29489501, 0.81033611],
       [0.92933312, 0.28962428, 0.50480061, 0.97575003, 0.30676499],
       [0.15843057, 0.24986663, 0.15318215, 0.51171144, 0.19834456],
       [0.15863201, 0.56060046, 0.99896885, 0.92428774, 0.58047529],
       [0.06532111, 0.70728976, 0.86449164, 0.37043458, 0.44586781]])

In [32]:
temp = a[0,:].copy()
a[0,:] = a[1,:].copy()
a[1,:] = temp
a

array([[0.92933312, 0.28962428, 0.50480061, 0.97575003, 0.30676499],
       [0.60248234, 0.0221739 , 0.96911108, 0.29489501, 0.81033611],
       [0.15843057, 0.24986663, 0.15318215, 0.51171144, 0.19834456],
       [0.15863201, 0.56060046, 0.99896885, 0.92428774, 0.58047529],
       [0.06532111, 0.70728976, 0.86449164, 0.37043458, 0.44586781]])

In [33]:
# 或者
a[[1,0,2,3,4]]

array([[0.60248234, 0.0221739 , 0.96911108, 0.29489501, 0.81033611],
       [0.92933312, 0.28962428, 0.50480061, 0.97575003, 0.30676499],
       [0.15843057, 0.24986663, 0.15318215, 0.51171144, 0.19834456],
       [0.15863201, 0.56060046, 0.99896885, 0.92428774, 0.58047529],
       [0.06532111, 0.70728976, 0.86449164, 0.37043458, 0.44586781]])

（10）把一个10\*2的随机生成的笛卡尔坐标转换成极坐标。

In [54]:
#笛卡尔坐标
a = np.random.randint(1,10,(10,2))
#极坐标
x = a[:,0]
y = a[:,1]
r = np.sqrt(x**2+y**2)  #距原点距离
R = np.arctan(y/x)  #弧度
# zip打包可迭代对象，成元组
result = np.array(list(zip(r,R)))
result

array([[8.24621125, 0.24497866],
       [9.21954446, 0.21866895],
       [9.43398113, 0.55859932],
       [8.24621125, 1.32581766],
       [7.28010989, 1.29249667],
       [9.48683298, 1.24904577],
       [9.43398113, 0.55859932],
       [2.82842712, 0.78539816],
       [9.21954446, 1.35212738],
       [6.70820393, 1.10714872]])

（11）创建一个长度为10并且除了第五个值为1其余的值为2的向量。

In [56]:
a = 2*np.ones(10,dtype=int)
a[4] = 1
a

array([2, 2, 2, 2, 1, 2, 2, 2, 2, 2])

（12）创建一个长度为10的随机向量，并求其累计和。

In [58]:
a = np.random.random(10)
result = a.cumsum()
print(a,result)

[0.25596392 0.72113432 0.41094441 0.43341599 0.34410093 0.74385886
 0.33760945 0.5199929  0.73506026 0.0285613 ] [0.25596392 0.97709825 1.38804266 1.82145865 2.16555958 2.90941844
 3.24702789 3.76702079 4.50208105 4.53064235]


（13）将数组中的所有奇数替换成-1。

In [59]:
a = np.random.randint(1,10,10)
a[(a%2) != 0] = -1
a

array([ 8, -1,  2,  4, -1, -1,  8,  2,  8, -1])

（14）构造两个4乘3的二维数组，按照3种方法进行连接？

In [60]:
a = np.random.random((4,3))
b = np.random.random((4,3))

In [62]:
r1 = np.vstack((a,b))
r1

array([[0.9825212 , 0.467519  , 0.44211588],
       [0.6719971 , 0.70231304, 0.43271449],
       [0.76789635, 0.53675558, 0.02645875],
       [0.03953407, 0.52990524, 0.30806891],
       [0.51968613, 0.34209458, 0.50333274],
       [0.86784388, 0.90798242, 0.13605725],
       [0.38215051, 0.57805035, 0.71172643],
       [0.37464826, 0.37457617, 0.29587104]])

In [64]:
r2 = np.hstack((a,b))
r2

array([[0.9825212 , 0.467519  , 0.44211588, 0.51968613, 0.34209458,
        0.50333274],
       [0.6719971 , 0.70231304, 0.43271449, 0.86784388, 0.90798242,
        0.13605725],
       [0.76789635, 0.53675558, 0.02645875, 0.38215051, 0.57805035,
        0.71172643],
       [0.03953407, 0.52990524, 0.30806891, 0.37464826, 0.37457617,
        0.29587104]])

In [66]:
r3 = np.dstack((a,b))
r3

array([[[0.9825212 , 0.51968613],
        [0.467519  , 0.34209458],
        [0.44211588, 0.50333274]],

       [[0.6719971 , 0.86784388],
        [0.70231304, 0.90798242],
        [0.43271449, 0.13605725]],

       [[0.76789635, 0.38215051],
        [0.53675558, 0.57805035],
        [0.02645875, 0.71172643]],

       [[0.03953407, 0.37464826],
        [0.52990524, 0.37457617],
        [0.30806891, 0.29587104]]])

（15）获取数组 a 和 b 中的共同项（索引位置相同，值也相同）。
a = np.array([1,2,3,2,3,4,3,4,5,6])，b = np.array([7,2,10,2,7,4,9,4,9,8])

In [67]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
c = a-b
a[c==0]

array([2, 2, 4, 4])

（16）从数组 a 中提取 5 和 10 之间的所有项。a=np.array([7,2,10,2,7,4,9,4,9,8])

In [68]:
a = np.array([7,2,10,2,7,4,9,4,9,8])
a[(a>5)&(a<10)]

array([7, 7, 9, 9, 8])